//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EvidenceReference) DeepCopyInto(out *EvidenceReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EvidenceReference.
func (in *EvidenceReference) DeepCopy() *EvidenceReference {
	if in == nil {
		return nil
	}
	out := new(EvidenceReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessInstallation) DeepCopyInto(out *HarnessInstallation) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessInstallation.
func (in *HarnessInstallation) DeepCopy() *HarnessInstallation {
	if in == nil {
		return nil
	}
	out := new(HarnessInstallation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HarnessInstallation) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessInstallationList) DeepCopyInto(out *HarnessInstallationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HarnessInstallation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessInstallationList.
func (in *HarnessInstallationList) DeepCopy() *HarnessInstallationList {
	if in == nil {
		return nil
	}
	out := new(HarnessInstallationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HarnessInstallationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessInstallationSpec) DeepCopyInto(out *HarnessInstallationSpec) {
	*out = *in
	out.TrustRef = in.TrustRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessInstallationSpec.
func (in *HarnessInstallationSpec) DeepCopy() *HarnessInstallationSpec {
	if in == nil {
		return nil
	}
	out := new(HarnessInstallationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HarnessInstallationStatus) DeepCopyInto(out *HarnessInstallationStatus) {
	*out = *in
	if in.CurrentReleaseDigest != nil {
		in, out := &in.CurrentReleaseDigest, &out.CurrentReleaseDigest
		*out = new(string)
		**out = **in
	}
	if in.LastGoodReleaseDigest != nil {
		in, out := &in.LastGoodReleaseDigest, &out.LastGoodReleaseDigest
		*out = new(string)
		**out = **in
	}
	if in.LastTransitionAt != nil {
		in, out := &in.LastTransitionAt, &out.LastTransitionAt
		*out = (*in).DeepCopy()
	}
	if in.EvidenceRefs != nil {
		in, out := &in.EvidenceRefs, &out.EvidenceRefs
		*out = make([]EvidenceReference, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HarnessInstallationStatus.
func (in *HarnessInstallationStatus) DeepCopy() *HarnessInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(HarnessInstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleBinding) DeepCopyInto(out *LifecycleBinding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleBinding.
func (in *LifecycleBinding) DeepCopy() *LifecycleBinding {
	if in == nil {
		return nil
	}
	out := new(LifecycleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleProjection) DeepCopyInto(out *LifecycleProjection) {
	*out = *in
	out.Metadata = in.Metadata
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleProjection.
func (in *LifecycleProjection) DeepCopy() *LifecycleProjection {
	if in == nil {
		return nil
	}
	out := new(LifecycleProjection)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleProjectionMetadata) DeepCopyInto(out *LifecycleProjectionMetadata) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleProjectionMetadata.
func (in *LifecycleProjectionMetadata) DeepCopy() *LifecycleProjectionMetadata {
	if in == nil {
		return nil
	}
	out := new(LifecycleProjectionMetadata)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LifecycleProjectionSpec) DeepCopyInto(out *LifecycleProjectionSpec) {
	*out = *in
	out.Binding = in.Binding
	if in.CurrentReleaseDigest != nil {
		in, out := &in.CurrentReleaseDigest, &out.CurrentReleaseDigest
		*out = new(string)
		**out = **in
	}
	if in.LastGoodReleaseDigest != nil {
		in, out := &in.LastGoodReleaseDigest, &out.LastGoodReleaseDigest
		*out = new(string)
		**out = **in
	}
	if in.EvidenceRefs != nil {
		in, out := &in.EvidenceRefs, &out.EvidenceRefs
		*out = make([]EvidenceReference, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LifecycleProjectionSpec.
func (in *LifecycleProjectionSpec) DeepCopy() *LifecycleProjectionSpec {
	if in == nil {
		return nil
	}
	out := new(LifecycleProjectionSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TrustReference) DeepCopyInto(out *TrustReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TrustReference.
func (in *TrustReference) DeepCopy() *TrustReference {
	if in == nil {
		return nil
	}
	out := new(TrustReference)
	in.DeepCopyInto(out)
	return out
}
